name: Tests

on:
  - push
  - pull_request

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1.0.6
        with:
          version: nightly

      - name: Clone repo with submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Node
        uses: actions/setup-node@v2

      - name: Install Yarn
        run: npm i -g yarn

      - name: Install Deps
        run: make

      - name: Config
        run: forge config

      - name: Lint
        run: yarn lint:check

      - name: Test
        run: forge test --gas-report --sizes
